---
title: "About"
---

## Background 

I grew up in Lahore Pakistan during my early childhood. During 2006, I moved to 
Vancouver with my family to discover new opportunties. I studied at a private religious school during elementary and 
completed an accelerated learning program at Palmer Secondary in Richmond, BC during high school. For my undergrad, I went to SFU and completed
my bachelors in Data Science with a minor in Computer Science. Before starting the MDS program, I worked on building small projects
that might help make my portfolio more applicable to entry level positions, some included a personal wesbite, an terminal command that auto applies to job 
positions, and more.

## Why Data Science 

What drew me to apply for the MDS program at UBC was more than just the degree and the title. Throughout my 
undergrad, I always wanted to study at one of Canadas top universities. I also enjoy meeting new people, learning new things, and 
building my professional network. These are some aspects that made me wnat to join a closely connected program where students can study together and 
learn from each other. I also enjoy the aspect of collaboration and problem solving that holds a big part of Data Science. 

## Outside of Data Science

Outside of academia, I enjoy playing badminton and going out to eat whenever I feel down or 
sick of schoolwork. I enjoy listening to classical music (particulary on piano). I hope to learn the piano one day to help
improve my coordination and rythm. On the weekends, I like to hang out with friends, play games, and go on the occasional hike here and there
around Squamish and North Vancouver. 
